[build-system]
requires = ["setuptools", "setuptools-scm", "wheel", "pip"]
build-backend = "setuptools.build_meta"

[project]
name = "sdbx"
dynamic = ["version", "dependencies"]
description = "A powerful and modular stable diffusion GUI with a graph/nodes interface."
authors = [
    { name = "darkshapes" },
]
requires-python = ">= 3.11"

[project.optional-dependencies]
core = [
    # PyTorch extensions
    # (torch, torchvision, and torchaudio version are determined by system in setup.py)
    "diffusers",
    "transformers",
    "accelerate",
    "peft",

    # Other machine learning libraries
    "llama-cpp-python",
    "scipy",

    # Graph data structure
    "networkx",

    # Server libraries
    "fastapi",
    "uvicorn",
    "watchfiles",
    "websockets",

    # Environment management
    "dulwich",
    "virtualenv",

    # Data validation
    "pydantic",
    "pydantic_settings",
]
dev = [
    # Testing frameworks and tools
    "pytest",
    "pytest-asyncio",
]

[project.scripts]
sdbx = "sdbx.__main__:main"

[tool.setuptools]
packages = ["sdbx"]

[tool.setuptools_scm]
