[extensions]
disable = false # [default false] Toggle extensions. false | "clients" | "nodes" | true

[location] # Assigned paths for loading and saving = "c:\\foo\\bar" or "..\\foo\\bar" | "/user/username/foo/bar" or "../foo/bar"
output  = "output"   # [default "output"]
clients = "clients"  # [default "clients"]
nodes   = "nodes"    # [default "nodes"]
flows   = "flows"    # [default "flows"]
input   = "input"    # [default "input"]
models  = "models"   # [default "models]

[web]                           # http:   //listen:port and related settings. IPv4 format.
listen         = "127.0.0.1"    # [default "127.0.0.1"] Service address. Accept all local connections using "" or "0.0.0.0"
port           = 8188           # [default 8188] Server port.
reload         = true           # [default true] Changes to source or user config directories reloads server.
reload-include = [ "*.toml", "*.json", "models/**/*" ] # Glob matches that reload above. [default "*.toml", "*.json", "models/**/*" ]
external-address = "localhost"  # [default "localhost"] URL for external API, such as image paths.
max-upload-size  = 100          # [default 100] Maximum file import size.
auto-launch      = true         # [default true] Shadowbox opens default browser when started.
known-models     = true         # [default true] Trigger model scanning when started

[computational]         # Settings that directly affect inference computation
deterministic = false   # [default false] Use slower deterministic algorithms. Determinism not guaranteed. CUDA only.

[memory]                    # RAM management
system-profiling = true     # [default true] Prevent OOM out-of-memory errors by measuring system GPU and CPU in advance.
# channels-first   = false    # [default false] Toggles channels last memory format when inferencing the models.
