models = [
    "alignment",            # controlnet, t2i adapters. photomaker, detectors, and classifiers
    "civit",                # civit.green downloads
    "diffusers",            # diffusion models, image weights
    "embeddings",           # textual embedding.
    "hypernetworks",        # similar to lora and textual embedding
    "huggingface",          # huggingface downloads and cache
    "loras",                # loras, all extension
    "llms",                 # GGGGGGGGGGGGGGGGUF 
    "metadata",             # metadata and model specification files
    "style_models",         # wildcards, style models
    "transformers",         # text transformers and CLIP 
    "upscale",              # "its not called upscale, its called SR!!!! Super Resolution!!!" - EXDYSA
    "vae",                  # vae incl TAESD
]